# Generated by Django 5.0.4 on 2024-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='100 рублей', max_length=255, verbose_name='Цена продукта'),
            preserve_default=False,
        ),
    ]
