# Generated by Django 5.0.4 on 2024-05-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='data',
            new_name='date',
        ),
    ]
